services:
  calcular-service:
    build:
      dockerfile: ./docker/DockerfileCalcular
    container_name: calcular-service
    depends_on:
      - rabbitmq
    networks:
      - internal
    volumes:
      - ./simulador-backend:/var/www/html/simulador-backend

  email-service:
    build:
      dockerfile: ./docker/DockerfileEmail
    container_name: email-service
    depends_on:
      - rabbitmq
    networks:
      - internal
    volumes:
      - ./simulador-backend:/var/www/html/simulador-backend
  
  notifica-ente-service:
    build:
      dockerfile: ./docker/DockerfileNotificaEnte
    container_name: notifica-ente-service
    depends_on:
      - rabbitmq
    networks:
      - internal
    volumes:
      - ./simulador-backend:/var/www/html/simulador-backend

  atualiza-margem-service:
    build:
      dockerfile: ./docker/DockerfileMargem
    container_name: atualiza-margem-service
    depends_on:
      - rabbitmq
    networks:
      - internal
    volumes:
      - ./simulador-backend:/var/www/html/simulador-backend

  simulador-service:
    build:
      dockerfile: ./docker/DockerfileSimulador
    ports:
      - "8181:8181"
    container_name: simulador-service
    depends_on:
      - rabbitmq
      - mysql
    volumes:
      - ./simulador-backend:/var/www/html/simulador-backend
    networks:
      - internal
    
  rabbitmq:
    image: rabbitmq:3-management
    hostname: my-rabbit
    container_name: rabbitmq_management
    
    ports:
      - "15672:15672"
      - "5672:5672"
    
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_HOST=/
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - internal
  
  mysql:
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: simulador
    container_name: mysql
    networks:
      - internal
    # command: --init-file=/docker-entrypoint-initdb.d/teste.sql

volumes:
  rabbitmq_data:

networks:
  internal:
    driver: bridge